name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [16, 18]
        operating-system: [ubuntu-latest, macOS-latest]
        include:
          - node-version: 18
            operating-system: windows-latest
        exclude:
          - node-version: 16
            operating-system: macOS-latest
    runs-on: ${{ matrix.operating-system}}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
